---
title: "Gov 50 Final Project"
author: "Luca Ace-Nasteski"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

```{r}

library(tidyverse)
library(ggplot2)
library(haven)
library(dplyr)

wave28 <- read_sav("wave28.sav")

wave28

```

COMTYPE2:
1. Urban
2. Suburban
3. Rural

```{r}
wave28 <- wave28 |>
  mutate(living_type = if_else(COMTYPE2F2_W28 == 1, "Urban",
                       if_else(COMTYPE2F2_W28 == 2, "Suburban",
                               if_else(COMTYPE2F2_W28 == 3, "Rural", "No Response"))))

wave28 <- wave28 |>
  mutate(parent_marital_status = if_else(FAM2_W28 == 1, "Married",
                                     if_else(FAM2_W28 == 2, "Divorced",
                                     if_else(FAM2_W28 == 3, "Seperated",
                                     if_else(FAM2_W28 == 4, "Widowed",
                                     if_else(FAM2_W28 == 5, "Never Married","No Response"))))))

wave28 <- wave28 |>
  mutate(thermo_republicans = case_when(
    is.na(THERMO_THERMBA_W28) ~ "No Response",
    THERMO_THERMBA_W28 <= 25 ~ "Very Cold and Negative", 
    THERMO_THERMBA_W28 > 25 & THERMO_THERMBA_W28 < 50 ~ "Somewhat Cold and Negative",
    THERMO_THERMBA_W28 == 50 ~ "Neither Positive or Negative", 
    THERMO_THERMBA_W28 > 50 & THERMO_THERMBA_W28 < 75 ~ "Somewhat Warm and Positive",
    THERMO_THERMBA_W28 >= 75 & THERMO_THERMBA_W28 <= 100  ~ "Very Warm and Positive"
  ))

wave28 <- wave28 |>
  mutate(thermo_democrats = case_when(
    is.na(THERMO_THERMBB_W28) ~ "No Response",
    THERMO_THERMBB_W28 <= 25 ~ "Very Cold and Negative", 
    THERMO_THERMBB_W28 > 25 & THERMO_THERMBB_W28 < 50 ~ "Somewhat Cold and Negative",
    THERMO_THERMBB_W28 == 50 ~ "Neither Positive or Negative", 
    THERMO_THERMBB_W28 > 50 & THERMO_THERMBB_W28 < 75 ~ "Somewhat Warm and Positive",
    THERMO_THERMBB_W28 >= 75 & THERMO_THERMBB_W28 <= 100 ~ "Very Warm and Positive"
  ))

wave28 <- wave28 |>
  mutate(gender = if_else(F_SEX_FINAL == 1, "Male", "Female"))

wave28
```

```{r}

perc_parent_marital_status <- wave28 |>
  filter(parent_marital_status != "No Response") |>
  group_by(parent_marital_status) |>
  summarize(count = n()) |>
  mutate(perc_parent_marital_status = count / sum(count))

perc_parent_marital_status

perc_thermo_republicans <- wave28 |>
  filter(thermo_republicans != "No Response") |>
  group_by(thermo_republicans) |>
  summarize(count = n()) |>
  mutate(perc_thermo_republicans = count / sum(count))

perc_thermo_republicans

perc_thermo_democrats <- wave28 |>
  filter(thermo_democrats != "No Response") |>
  group_by(thermo_democrats) |>
  summarize(count = n()) |>
  mutate(perc_thermo_democrats = count / sum(count))

perc_thermo_democrats
```

```{r}

perc_living_type <- wave28 |>
  filter(living_type != "No Response") |>
  group_by(living_type) |>
  summarize(count = n()) |>
  mutate(perc_living_type = count / sum(count))

perc_living_type

perc_living_type |>
  ggplot(mapping = aes(x = fct_reorder(living_type, perc_living_type),
                       y = perc_living_type)) +
  geom_col(mapping = aes(fill = living_type)) +
  labs(x = "Living Type",
       y = "Percentage", title = "Description of Community Where Surveyent Currently Lives")



```



```{r}

perc_parent_marital_status |>
  ggplot(mapping = aes(x = fct_reorder(parent_marital_status, perc_parent_marital_status), 
                      y = perc_parent_marital_status)) + 
  geom_col(mapping = aes(fill = parent_marital_status)) + 
  labs(x = "Parent Marital Status", 
       y = "Percentage", title = "Marital Status of Parents During Most of Their Time Growing Up")

```

```{r}
wave28 |>
  filter(THERMO_THERMBA_W28 >= 0 & THERMO_THERMBA_W28 <= 100) |>
  summarize(mean_thermo_republicans = mean(THERMO_THERMBA_W28, na.rm = TRUE))

wave28 |>
  filter(THERMO_THERMBA_W28 >= 0 & THERMO_THERMBA_W28 <= 100) |>
  summarize(mean_thermo_democrats = mean(THERMO_THERMBB_W28, na.rm = TRUE))
```


```{r}

republicans <- wave28 |>
  filter(parent_marital_status != "No Response") |>
  group_by(parent_marital_status, gender) |>
  summarize(mean_thermo_republicans = mean(THERMO_THERMBA_W28, na.rm = TRUE)) 

democrats <- wave28 |>
  filter(parent_marital_status != "No Response") |>
  group_by(parent_marital_status, gender) |>
  summarize(mean_thermo_democrats = mean(THERMO_THERMBB_W28, na.rm = TRUE))

republicans1 <- wave28 |>
  filter(living_type != "No Response") |>
  group_by(living_type, gender) |>
  summarize(mean_thermo_republicans = mean(THERMO_THERMBA_W28, na.rm = TRUE))
  
republicans

republicans1

democrats

```


```{r}

ggplot(republicans, aes(x = parent_marital_status, y = mean_thermo_republicans, fill = parent_marital_status)) +
  geom_col(stat = "identity", position = "dodge", alpha = 0.8) +
  facet_grid(rows = vars(gender)) +
  labs(x = "Parent Marital Status", y = "Mean Thermo Republicans", title = "Comparison of Mean Thermo towards Republicans by Marital Status")

ggplot(democrats, aes(x = parent_marital_status, y = mean_thermo_democrats, fill = parent_marital_status)) +
  geom_col(stat = "identity", position = "dodge", alpha = 0.8) + 
  facet_grid(rows = vars(gender)) + 
  labs(x = "Parent Marital Status", y = "Mean Thermo Republicans", title = "Comparison of Mean Thermo towards Democrats by Marital Status")

```





```{r}

ggplot(republicans1, aes(x = living_type, y = mean_thermo_republicans, fill = living_type)) +
  geom_col(stat = "identity", position = "dodge", alpha = 0.8) + 
  labs(x = "Parent Marital Status", y = "Mean Thermo Republicans", title = "Comparison of Mean Thermo towards Republicans by Marital Status")

  
  
  

```



